### PR TITLE
OU-539: Dynamically Reload Certificates 

### PR DESCRIPTION
**Pull request by zhuje**
### JIRA 
https://issues.redhat.com/browse/OU-576

### Related Issues
Based on modifications from monitoring-plugin: https://github.com/openshift/monitoring-plugin/pull/264

QE subtask: 
[OU-575](https://issues.redhat.com/browse/OU-575)

### Demo
https://drive.google.com/file/d/1HV_tQfFfcmJT58buIbgFZAKCSDdT7KVL/view?usp=sharing
Figure 1. Video demo (~3 min). Shows TLS certificates being dynamically reloaded. Shows troubleshooting panel pod logs that describe the reason for reloading and shows new certificate present in a pod using `openssl s_client.` 

/hold 
For QE testing

### CODE REVIEW

**Comment by zhuje** [comment]
/hold

/cc @anpingli
This PR is trying to address [OU-576](https://issues.redhat.com/browse/OU-576). Could you test it?

**Comment by zhuje** [comment]
/cc @anpingli 

I pushed some changes, could you test this PR?

**Comment by anpingli** [comment]
Test pass, LGTM

**Comment by anpingli** [comment]
LGTM

**Pull request merged**
